Add signature DER decoding
Sajjon/EllipticCurveKit pull request #17
Opened 2021-02-21 18:24 UTC by jnordberg

Re-submit of #15

2021-02-21 18:32 UTC, Sajjon requested changes
nice! I would really like to see some unit tests first though! Thanks for submitting this! Will review faster this time - LOL!

2021-02-21 18:32 UTC, Sajjon commented on Sources/EllipticCurveKit/Encoding/DER.swift
> +public func derDecode(data: Data) -> (r: Number, s: Number)? {
If this function where to throw instead of returning an optional, the user can get info about what was wrong (about the input). 

Also might be worth introducing a namespace for `DER` now, let's go with:

```
/// DER decoding and encoding 
public enum DER {} // just a namespace

public extension DER {
    static func decode() throws -> (r: Number, s: Number) ...
    static func encode(r: Number, s: Number) -> String
}
```

2021-02-21 18:32 UTC, Sajjon commented on Sources/EllipticCurveKit/Encoding/DER.swift
> +    let rLen = Int(data[3])
let's spell things out - that's the swift way :D `rByteCount`?

2021-02-22 07:18 UTC, jnordberg commented on Sources/EllipticCurveKit/Encoding/DER.swift
> +public func derDecode(data: Data) -> (r: Number, s: Number)? {
I had the same thought when writing this but opted to make the change as minimal as possible and try to follow the existing conventions in the codebase.

2021-02-22 07:23 UTC, jnordberg commented
Thanks! Added a test case for the existing DER encoding function as well as the decoding function introduced by this patch. I'll let you handle any refactoring of the component, encapsulating it in a namespace sounds like a good idea ;)

2021-02-22 12:35 UTC, Sajjon commented on Sources/EllipticCurveKit/Encoding/DER.swift
> +public func derDecode(data: Data) -> (r: Number, s: Number)? {
Sure, I can make those changes, thanks!

2021-02-22 12:35 UTC, Sajjon approved these changes
Thanks for your contribution! 


Off-Topic: Would be happy to know if/how you use this SDK? :)

2021-02-22 12:35 UTC, merged

2021-02-22 23:24 UTC, jnordberg commented
We use it in a EOSIO wallet (Anchor Wallet on iOS AppStore if you want to check it out) to do ECDSA pubkey recovery on signatures generated in the Secure Enclave. EOSIO supports both secp256r1 and secp256k1 although r1 support is still not widely adopted on the web-side so it's still an experimental feature hidden behind an app setting :)